swagger: '2.0'
schemes:
  - https
host: acme.pinn.ai
basePath: /
info:
  description: |
    The ACME Bank backend is a demonstrable web server that provides a 
    REST API for both registration and login. Its main purpose is to be
    a consumer of the Pinn hosted REST APIs. Its major functionality is
    supporting the registration of new users (and enrolling their biometrics),
    as well as authetnicating a user with both biometrics and traditional
    credentials
  version: '0.1.0'
  title: ACME Bank API
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
produces:
  - application/json
consumes:
  - application/json

tags:
  - name: Register
    description: Create and enroll an ACME Bank end user
  - name: Login
    description: Authenticate and verify an ACME Bank end user

paths:
  '/register':
    post:
      tags:
        - Register
      summary: Sign up endpoint for new users
      description: This endpoint creates and persists the user, sets their
       chosen password, and finally enroll their biometric data
      operationId: register
      parameters:
        - in: body
          name: body
          description: Parameters for user registration
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
                description: Username supplied by the end user registering
              password:
                type: string
                description: Password supplied by the end user for credential auth
              left_palm:
                type: string
                description: Base64 encoded JPEG data of the left palm capture image
              right_palm:
                type: string
                description: Base64 encoded JPEG data of the right palm capture image
      responses:
        '200':
          description: Ok
          schema: 
            $ref: '#/definitions/User'
          examples:
            application/json:
              id: 1
              username: dmwesterhoff
              pinn_user_id: usr_RMcDzQsFw6g7lhmk
              object: user
              created: 1533171964
        '400':
          description: Bad Request
        '422':
          description: Palm Not Found
  '/login':
    post:
      tags:
        - Login
      summary: A sign in endpoint for existing users
      description: This endpoint "logs in" a user with their existing credentials and captured biometric data
      operationId: login
      parameters:
        - in: body
          name: body
          description: Authentication parameters
          schema:
            type: object
            required:
              - username
              - password
              - palm
            properties:
              username:
                type: string
                description: Username supplied by the end user logging in
              password:
                type: string
                description: Password supplied by the end user logging in
              palm:
                type: string
                description: Base64 encoded JPEG data of the left or right palm capture image
      responses:
        '200':
          description: Ok
          schema: 
            $ref: '#/definitions/User'
          examples:
            application/json:
              id: 1
              username: dmwesterhoff
              pinn_user_id: usr_RMcDzQsFw6g7lhmk
              object: user
              created: 1533171964
        '400':
          description: Bad Request
        '422':
          description: Palm Not Found

definitions:
  User:
    type: object
    properties:
      id:
        description: Unique identifier for the ACME Bank user
        type: integer
        minLength: 1
        example: 1
      username:
        description: User supplied username
        type: string
        minLength: 4
        example: dmwesterhoff
      pinn_user_id:
        description: The Pinn user identifier, created by Pinn API at the time of user creation
        type: string
        example: usr_RMcDzQsFw6g7lhmk
      object:
        description: The type of object, which is always `user`
        type: string
        example: user
      created:
        description: Timestamp of creation, an integer that is the number of seconds since unix epoch
        type: integer
        example: 1533171964

